import DesktopNav from "@/components/DesktopNav";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="flex h-screen bg-background">
      <div className="w-64">
        <DesktopNav />
      </div>
      <div className="mx-auto max-w-6xl flex-1 px-10 py-8">{children}</div>
    </div>
  );
}
